name = "breadrot"
version = "0.1.0"
rust-version = "1.61"
authors = ["Localbox Crox <hman@hman.io>"]
license = "BSD-3-Clause"
description = "a collection of simulators for microprocessors in rust"
keywords = ["spotify"]
repository = "https://github.com/DaBigBlob/breadRot"
readme = "README.md"
edition = "2021"


[lib]
name = "librespot"
path = "src/lib.rs"

[[bin]]
name = "librespot"
path = "src/main.rs"
doc = false